sh_test(
    name = "float_array_test",
    args = ["$(location //:main)", "test/float_array"],
    srcs = ["test.sh"],
    size = "small",
    data = [
        "//:main",
    ],
)

sh_test(
    name = "uint_array_test",
    args = ["$(location //:main)", "test/uint_array"],
    srcs = ["test.sh"],
    size = "small",
    data = [
        "//:main",
    ],
)
