alias(
    name = "this",
    srcs = ":wasm_toolchain",
)

exports_files(
    [
        "emscripten-repo.bzl",
        "condition-include.bzl",
        "vars.bzl",
    ],
    visibility = "//visibility:public",
)
