* Mechanics
** Actions
*** Camouflage
	Cannot be seen until close
*** Attack
	Removes sectors
*** Add
	Adds sectors
*** Increase
	Increases max sector count
*** Poison
	Set damage rate over time
*** Control
	Temporarily Gain Control Over Enemy Piece
*** Sight
	See Camo'd enemy
*** Speed
	Increase speed of unit
*** Slow
	Decrease speed of unit
*** Flip Tile
	Make a tile exist, or remove one from existence
** Targetting 
   Can target foe or friend or self
** Moving
*** Manhatten
	decrease x/y distance
*** A Star
	Paths to player
*** DONE Heal Player as Move
	 CLOSED: [2018-06-10 Sun 14:40]
** TODO Level Goals
   Level Goals that you have to capture while enemies are still alive.
   Perhaps some story state events can be triggered on victory type. Obviously at the very least victories will add credits and unlock connected nodes.a
*** Information
	We want information [Prisoner refernce]
	Perhaps it will lend some competitive advantage?
	Perhaps it will allow you to see the stats of enemy units?
*** Encryption Key
	Data should have a variety of keys that can be acquired to unlock the contents of information
** Online Conversation w/ Joel
*** Efficiency
Yes I too was caught up on efficiency. For this run, I'm going with a MAKE IT WORK EASY. Coding time spent and ease of re-use are far more important that efficiency, and I understand this now.

*** Classes
yeah, for me in my old full C++ version i was going to have AIs be parameters for the classes (function pointers, or class pointers), and attacks and such would also be function pointers. Same's going to go on with this new one, but it will be done in Lua so like no nasty type-signatures.

*** State Machine
Yeah I had a state machine deciding on what to do in C++. I'll put a more refined and hidden concept of state into my Lua version.

*** Custom Coded UI
Yuppers - that's the current part I'm at rn, but with the 'who cares about efficiency' mentality, it's going to be easy. I'm almost done now that I have line-wrapping text rendering in boxes. As far as resizing, I'm probably going to say components can have a custom resizing handler as I don't feel like it's necessary to rewrite CSS. I will at least provide snap to % along top,left,right,or bottom, text alignment, and such. So it will have like most of the necessary things for a game, and custom handlers for when that's not enough. I also probably want to insert an in-game console, but that's a stretch goal.

*** Real Programming Language
Yeah. Me too with GameMaker then concluding it's not real enough, but like I need to also make my younger self proud and pull this off the right way.

*** Flying Solo (Or not)
I normally fly solo only because when I started freshman year of HS there wasn't anyone else my age I knew programming and willing to reach for the stars. In college, everyone else was either dying of work, or had their own projects. I fit into both categories, but hey I have time now. Anyways I like teams as long as it's Agile, and I have a guy who likes making games joining this project to work on story, and my brother who can't program will be doing level design as he likes that and also wants more Nightfall. You're free to join me Joel, but I would recommend waiting until I have it ready for a demo so that the basic utilities like buttons, level-maps, and battles work decently well, so that perhaps you could focus on some cool things you want to see like Proc-Gen Questing/Battles. The code is obviously open-source and is under the MIT license. Feel free to fork and make PRs at any time though. I may get an artist and/or a musician to work with me on the project as well. I like doing my own art, and can do my own music, but we shall see how that goes. I'll have less time when my real job starts next week, but it's a nice company so they won't work me past an 8-hour day, and that's less time than I was putting in towards school, so essentially I have lots of free time. Although there's other things in life that will take up my time like communing with fellow lesbians and whatnot, but again I'll have plenty of time to work on this cause I think it's cool and fun.

*** Quantum
kind of gimmicky - sounds cool at first, but would just be odd.

*** Concurrency @V2
good idea with critical section, adds another game mode.

*** Visual Style
I initially was going to do pixels, because that's one of the art styles I'm best at, but decided to go with SVG art converted to png. I do plan on using a pixel font (Mozart NBP). I really like the idea of different visual styles for different levels of technology across the web. My first game (second considering I'll be making a demo as v1) will take placed on an advanced military network, but great idea for the second game where you're released into the world.

*** Zones/Making lower programs worth it
what if each program has an associated file-size and the lower level versions are smaller often? zones with bad tech can't support more complex programs.

*** Skinning/Themes @V2
My code already supports map specific tilemaps, and slug sprites are also loaded from tilemap files, so it's easy to switch out - one of the reasons I used Lua was for easy data read in, and supporting Tiled means mods are easy. (That's another reason to use a scripting language, as it permits custom AI and game-modes).

*** Microcosm/Macrocosm
Agreed, Nightfall lacked inspiration, but was still great. I intend to improve on the macro with good storytelling and dialogue that matters. I even have a fellow game maker who I pitched the project to and he's excited for it and I think he'll write much of the actual dialogue and improve upon my story ideas.

*** Penalties
Good idea. There can be penalties and also the ability to save, so you can save-scum if you don't want to face them but they make the game more fun. I think 'programs that die in battle are dead' would be a good thing. It would give that 'leave' button more potential - if you withdraw from battle, you can save credits/programs that haven't been killed yet.

*** Proc-Gen Maps & Content @V2
My do I love proc-gen, but this definitely sounds like a reach goal for a v2 game.
** TODO Dialogue
   Generic dialogue nightfall style
*** Parse Dialogue From Orgmode File
*** Follow Normal Same-File
*** Special Lua-Link
	link: lua://filename#methodname
*** Special onload setup?
*** Conditionals, Variables?
*** Dialogue Trees?
	Perhaps have named dialogue events that options within the current dialogue can take you to?
** TODO Player State
   Slugs owned, credits, story state variables
   Save & Load
* Storyline
** Whose Side?
   Initially you start off on the Operator side. You are number 12. You use they/them pronouns. You are a person.
   Your side has buildings, your side has information. So does the other side
   You could go rogue if you wanted to. 
   There must be some punishment for going rogue early on. Some tools the enemy can provide.

** Main Idea - My Side From Conversatoin w/ Jake
Game's called *Operator 12* - you're in some mysterious and shadowy organization - you're #12 you report to #2 and #6 has gone rogue.

I'm thinking that we could do some great story telling here - the original one's dev's lacked in that area, and so my thought is that we can work out the broad storyline and then maybe start writing dialogue for it? You can also design levels of course - we'll need tons of them - the original game had far too few

all my thoughts as far as storyline is so you start fighting the enemy, because that's what you're told to do, and slowly you find out that the enemy defected because he learned what the organization is really about, what it hides behind a mask of uniform noise

so like the game functions around information

you're initially directed to fight against the enemy to take down their network but also to gather information that will help in defeating the enemy

and then the enemy presents you with the opportunity to do missions for information from your organization by hacking their systems so that your org can't tell that you've crossed them

and I'm thinking like option based dialogue, kind of like interactive story type dialogue? with the little text/face at the bottom and occasionally present options to the user for responses

and like main quest lines would either be defeat the enemy, capture him, and get him to tell why he defected, which would result in you winning the game, and then being 'reset' because you know too much ('you win popup' -> 'dialogue saying you know too much' -> 'credits' -> 'main menu' game would return to the main menu)

and the other thing of the story is that you're one of the most advanced military AI, but don't know it, because you start with a blank slate

and I'm feeling that over the course of the game, everyone you meet has little files on them giving their picture, bio, name, pronouns and everyone from your organization is just like 'operator #x, they/them, an agent of blah' and you can gain/choose your identity - the more you side with the enemy, the more you choose things about your own character, such as name, gender, whatever. Or you could choose to side with your people, and remain with an undefined identity.

and like if you play your cards right, maybe you can have another alternate ending where you become operator #2 or operator #1 even

and of course there's also the full defection ending where you take down your organization and learn you're an AI in a simulation connected to the internet

** Endings
*** Defect
	Learn you're a military AI by defeating Operators #11 thru #2 (or 1?)
*** Be Reset
	Play game normally, capture enemy, relate his information to #2
*** Become #2
	Do not collect information until you side with the enemy
	Do not choose an identity
	The enemy presents you with a tool to collect information without opening it
	The enemy presents the tool to attack your side without your side knowing it
	Collect info from the enemy and from your side
	The enemy presents you with a tool to read info without opening it
	Present specific bits of information to the operators that is specific to each one from lowest to highest
	After each one, you *reset them to your previous number* and say I am Operator X (assuming their number). They respond I am number Y (your previous number).
	You probably have to learn what the role associated with each rank is and tell them what your duty is, else you blow the Become #2 option?
	Skip #6
	And eventually you become #2, and learn who and what #1 is
*** Become #6
	Resetting #6 is a possibility after resetting #7
	Game ends - #2 declares a new public enemy - *YOU*
	
* Drawing Commands
** Map
   A map is the default drawing structure. It is scrollable, and contains objects by coordinates. It figures out what needs to be drawn and draws it.
*** Map Sprite
	Drawn to a map. Can be geometrical shape or png. Can fade in and out, but that's about it.
** TODO Glitch Screen
   1. Swap rendering context to a new Texture,
   2. Render screen
   3. Unset rendering
   4. Render texture to screen
   5. Take sections of the texture, shift their RGBA and render back to the screen
   
