load("//bzl:vars.bzl", "COPTS", "LINKOPTS")

cc_library(
    name = "include",
    srcs = glob([
        "*.hh",
    ]),
    includes = [""],
    copts = COPTS,
    linkopts = LINKOPTS,
    visibility = ["//visibility:public"],
)
