load("//bzl:vars.bzl", "COPTS", "LINKOPTS")

cc_library(
    name = "util",
    srcs = glob([
        "*.cc",
    ]),
    hdrs = glob([
        "*.hh",
    ]),
    copts = COPTS,
    linkopts = LINKOPTS,
    includes = [""],
    visibility = ["//visibility:public"],
)
