cc_library(
    name="lua-android-include",
    hdrs = ["android-lua.h"],
    includes = [""],
    visibility = ["//visibility:public"],
)

objc_library(
    name="lua-ios-include",
    textual_hdrs = ["ios-lua.h"],
    srcs = ["ios-lua.c"],
    includes = [""],
    visibility = ["//visibility:public"],
)

cc_library(
    name="gzip-ios-include",
    textual_hdrs = ["ios-gzip.h"],
    srcs = ["ios-gzip.c"],
    includes = [""],
    visibility = ["//visibility:public"],
)
